### ISSUE TITLE
"Hey" name is already established

### ISSUE THREAD

**Issue by notramo** [heyform/heyform#10]
The company [37signals](https://37signals.com) develops the [HEY](https://www.hey.com) email and HEY Calendar apps.

Then name of this project is confusing, as I initially thought it's a new product from 37signals.

This will cause confusion on the long run, causing annoyances both for this project and 37signals. It doesn't matter that both HEY Email and HeyForms are high quality products, it will probably cause worse brand awareness because of the confusion.

**Comment by dearroy** [comment]
Great find, @notramo!

Once we find the PMF, we'll seriously consider rebranding to something truly unique.  However, our current priority is to concentrate on building an exceptional product and ensuring its widespread appeal.

As long as people can search "HeyForm" and access our website or repository, we don't think it is fatal now.
