### ISSUE TITLE
Selfhosting instructions broken

### ISSUE THREAD

**Issue by Leopere** [heyform/heyform#112]
<img width="1236" alt="image" src="https://github.com/heyform/heyform/assets/1068374/58d23ccb-20f0-4817-89c8-cf1ebb47c339">

**To Reproduce**
1. Go to https://docs.heyform.net/local-development via the main README.md 
2. Click on https://github.com/heyform/heyform/blob/main/README.md?plain=1#L80
3. ....

**Expected behavior**
A clear and concise description of what you expected to happen:  something...

**Screenshots**
<img width="1116" alt="image" src="https://github.com/heyform/heyform/assets/1068374/74ca5d33-5719-425f-a927-54f0a5f24b5d">

**HeyForm (please complete the following information):**
- Install: Can't yet
- Version: N/A

**Comment by bperreault** [comment]
Hi, Leopere,
I'm not a dev, but was following this bug. I found this https://docs.heyform.net/open-source/local-development which may get you through till it's fixed in the docs.

**Comment by dearroy** [comment]
My fault.

I'm working on migrating the documentation from Notion to GitHub to enable collaborative contributions. I forgot to update the README link but will do so shortly.

**Comment by bperreault** [comment]
If it helps, I submitted a PR
