### ISSUE TITLE
Add hidden fields in CSV export

### ISSUE THREAD

**Issue by iMuFeng** [heyform/heyform#116]
### Discussed in https://github.com/orgs/heyform/discussions/111

<div type='discussions-op-text'>

<sup>Originally posted by **maximevalette** June 27, 2024</sup>
Hidden fields are very useful for us, could you add them as well in the CSV export file?</div>

**Comment by tcroue** [comment]
Also, could they be added in the webhooks ?

**Comment by fkammer** [comment]
Would be nice, if they could also be included in the emails sent out.

**Comment by fkammer** [comment]
@iMuFeng I opened three separate pull request to include hidden fields in
- csv exports
- emails (integration)
- webhooks (integration)

Would be awesome to see them in a release soon as we need to pass the hidden field values along with the answers to third parties by mail.
