### ISSUE TITLE
[Bug]: Submission count is higher than available results in csv export

### ISSUE THREAD

**Issue by tcroue** [heyform/heyform#117]
### Bug Description

As an admin, I want to see in my results (or CSV export), all the submissions (as counted on the analytics tab)

### Steps to Reproduce

I am an admin on the heyform account
I have created a heyform and first results came in around July 1st
On july 16th, I am trying to preview the results for [this specific form](https://heyform.gobetterway.fr/form/iUuhwaky)
I select the last 3 months in the date range picker, which should cover all the results received.
I find 99 results (both in the app and in the exports). No records prior to july 12th. (note: name of the form may have been changed on this day.)
We are 100% sure there were more records than this at some point.

### Expected Behavior

Find all 553 results

### Screenshots

![image](https://github.com/user-attachments/assets/5ceadc01-a200-4770-a74a-afb7f557d428)

### HeyForm Installation

self hosted

### Version

0.0.9

### Desktop OS

macOS

### Desktop Browser

Chrome

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by dearroy** [comment]
@tcroue Can you please try to make a new submission and see how these numbers change accordingly?

**Comment by tcroue** [comment]
Sure, 

It seems fine right now, 

Before:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/59aa1d2a-5d0a-4d44-99cb-be3bcbfe55fd">
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/d6a40d9f-5cb4-49b6-94ab-2d79106fd726">


After
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/572cfffd-223d-4373-a556-23e661a4f10c">
