### ISSUE TITLE
[BUG] Authentication Link keeps on loading cant sign in or login

### ISSUE THREAD

**Issue by dEvAshirvad** [heyform/heyform#12]
![Screenshot 2024-04-02 at 10 38 52 PM](https://github.com/heyform/heyform/assets/74089931/df6be14f-30fb-4d4b-9085-8e37d40877fe)

It's been 5 min but still loading

**Comment by dEvAshirvad** [comment]
As a student delving into the MERN stack, I've been actively seeking out open-source projects to expand my knowledge and offer my assistance. While exploring your project, I encountered an issue and I'm keen on lending a hand to resolve it. I believe that contributing to your project not only provides me with invaluable learning opportunities but also allows me to make a meaningful impact in the developer community.

**Comment by iMuFeng** [comment]
Please specify particular actions. My testing revealed no issues.

**Comment by kundan766** [comment]
hey, @dEvAshirvad Authentication is working absolutely fine .I think due to your network issue you face this problem

**Comment by Ehsankazazi** [comment]
### https://github.com/heyform/heyform/issues/12#issue-2221028934__

**Comment by Ehsankazazi** [comment]
#15

**Comment by silverfantacy** [comment]
I have the same problem.

**Comment by silverfantacy** [comment]
@dearroy No errors, just keep redirecting to the login.

**Comment by iMuFeng** [comment]
> @dearroy No errors, just keep redirecting to the login. If the account password is wrong, the password error will be displayed normally.

We have updated the [self hosting docs](https://docs.heyform.net/self-hosting#3292d2af2f3a48a8aa3a82c5a536fafb), please take a look.

**Comment by ElijahAhianyo** [comment]
same here. Its literally just stuck. Cant log in or sign up and my internet is really good

**Comment by AprilNEA** [comment]
I have found the actual problem and solved it. 

> I have the same problem. deployed using the zeabur template.

Make sure you have `APP_HOMEPAGE_URL` env var, and it's the same address you accessed.
