### ISSUE TITLE
[Bug]: As an admin, i want to open an attachment without being redirected to my workspace home page instead

### ISSUE THREAD

**Issue by tcroue** [heyform/heyform#120]
### Bug Description

While clicking on some attachments from subsmissions, i get redirected to the home page

### Steps to Reproduce

go to the submissions page
https://heyform.gobetterway.fr/workspace/EX0UvA2h/project/fYdwvvWX/form/A6VCl68K/submissions

click on one of the attachment
get redirected to the home page

### Expected Behavior

the attachment (pdf) is downloaded

### HeyForm Installation

self hosted

### Version

0.0.9

### Desktop OS

Windows

### Desktop Browser

None

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by iMuFeng** [comment]
Have you set `APP_HOMEPAGE_URL` to `https://heyform.gobetterway.fr` ?
