### ISSUE TITLE
[Bug]: Download csv is not working. 

### ISSUE THREAD

**Issue by touchty** [heyform/heyform#122]
### Bug Description

No file was downloaded after clicking the download button. 

### Steps to Reproduce

1. Self-host the service.
2. Add submission
3. Download the submission
4. No file should be downloaded. 

### Expected Behavior

A file should be downloaded. 

### HeyForm Installation

self hosted

### Version

master 5ada0bf

### Desktop OS

macOS

### Desktop Browser

Chrome

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

### Mobile Browser Version

127.0.6533.72 arm

**Comment by dearroy** [comment]
@touchty I can't reproduce the issue. Which version are you using? What error messages are showing in the console?

**Comment by touchty** [comment]
@dearroy Thanks for reply. The issue occurred in the dev ENV because of different ports used by the webapp and server. After adding server.proxy (**export**/*) to **vite.config.ts**, it works normally.
