### ISSUE TITLE
[Bug]: Workspace logo and user avatars don't load

### ISSUE THREAD

**Issue by mgmorcos** [heyform/heyform#139]
### Bug Description

Even though successful upload of workspace logo is verified in the filesystem, it won't load. User avatar from Google SSO also doesn't load.

### Steps to Reproduce

1. Run the latest self hosted docker compose set up, as documented but with Google login, as of today.
2. Sign in to Heyform with Google
3. Upload a workspace logo and create a workspace

### Expected Behavior

Workspace logo and user avatar load

### HeyForm Installation

self hosted

### Version

v0.0.13

### Desktop OS

macOS

### Desktop Browser

Chrome

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by iMuFeng** [comment]
I can't reproduce the issue. What error messages are showing in the console?
