### ISSUE TITLE
[Bug]: Hidden fields are not submitted to database

### ISSUE THREAD

**Issue by maximevalette** [heyform/heyform#143]
### Bug Description

Even well configured and filled, the hidden fields are not submitted on form validation

### Steps to Reproduce

1. Create a new form with a hidden field
2. See that the field is actually saved on the Creator interface
3. Test the form by specifying an hidden field value in GET parameter
4. The hidden value is not present in the Submissions interface

### Expected Behavior

The hidden fields should be correctly saved on form submission

### Screenshots

![image](https://github.com/user-attachments/assets/5e5f1fe1-a90d-4560-b29c-3bc08d41ad9c)

Hidden field correctly showing up in graphQL response:

![image](https://github.com/user-attachments/assets/f8989319-04b8-4e90-9e51-6461696b56ce)

![image](https://github.com/user-attachments/assets/c39cb984-3ba5-4f3a-a937-6bafc872cf82)

Submit payload:

![image](https://github.com/user-attachments/assets/660bb1a1-05e2-414a-937b-615c6f8c4919)

### HeyForm Installation

self hosted

### Version

0.0.14

### Desktop OS

macOS

### Desktop Browser

Chrome

### Desktop Browser Version

128

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by maximevalette** [comment]
FYI the most recent version with working hidden fields is 0.0.8.

**Comment by nemunaire** [comment]
I face the exact same problem

**Comment by fkammer** [comment]
We're having the same problem. My colleague @SiebelsTim created a PR to fix this. #150
