### ISSUE TITLE
[Bug]: Maximum Update Depth Exceeded in BackgroundBrightness Component

### ISSUE THREAD

**Issue by PiyushXmishra** [heyform/heyform#151]
### Bug Description

The BackgroundBrightness component is causing a "Maximum update depth exceeded" error in React. This happens when the component triggers an infinite loop of re-renders due to state updates in the onChange callback.

### Steps to Reproduce

1. Go to form creation page.
2. Rapidly move the slider (adjust brightness quickly).
3. Error page with Minified React error in console.

### Expected Behavior

The value should update without triggering a loop of state changes and re-renders.

### Screenshots

![image](https://github.com/user-attachments/assets/bf40a023-7e55-46d4-911b-68ddff836307)
![image](https://github.com/user-attachments/assets/980476c1-dbce-4b37-9b41-8f73ac9f6ce1)
![image](https://github.com/user-attachments/assets/43a59ff1-9859-4765-8873-ac45b20cadd7)

### HeyForm Installation

heyform.net

### Version

v0.0.14

### Desktop OS

Windows

### Desktop Browser

None

### Mobile Device

None

### Mobile OS

None

### Mobile Browser

None

**Comment by iMuFeng** [comment]
I was unable to reproduce this bug, but I will submit some code to attempt optimization.

**Comment by PiyushXmishra** [comment]
Thank you for the optimization update! Since I’m facing this issue on **heyform.net** (the production environment), could you let me know once the update is deployed there?

**Comment by iMuFeng** [comment]
We can only fully resolve this issue after radix-ui fixes it (https://github.com/radix-ui/primitives/issues/2717). For now, we can only implement temporary workarounds.

**Comment by PiyushXmishra** [comment]
Yeahh, it looks like the issue does originate from Radix UI and thanks for optimization!❤️. I’ll also keep an eye on the Radix UI issue for any permanent fix.
