### ISSUE TITLE
File upload is not working

### ISSUE THREAD

**Issue by MrCoder** [heyform/heyform#26]
**To Reproduce**
1. Go to 'https://hey.diagramly.ai/form/da8boDn2'
2. Click on 'Upload file'
3. Select a file
4. See file size is displayed but file is not uploaded.

**Expected behavior**
File is uploaded.

**Screenshots**

<img width="768" alt="image" src="https://github.com/heyform/heyform/assets/169417/100e38e5-9a79-48d2-9878-f8a54d898c1a">

**HeyForm (please complete the following information):**
- Install: Self-hosted
- Version: Not sure where to find the version. We hosted it with docker-compose. It was setup on 4th April 2024.

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Chrome
- Version: Version 123.0.6312.105 (Official Build) (arm64)

**Comment by iMuFeng** [comment]
The images will only start uploading after the form is submitted. I have tested it on Arc 1.37.0 (48361) and Chrome 123.0.6312.105 (Official Build) (arm64):

![image](https://github.com/heyform/heyform/assets/1407009/bf11852e-093e-4f6b-884b-bff8cfb3b194)

**Comment by zacker330** [comment]
I had double check this issue. Yes, as your screenshot demonstrating the image was uploaded successfully. 

But the issue is that we can't download it by clicking the attachment icon on the submissions page, which is showing all data as a table for the form admin.


> The images will only start uploading after the form is submitted. I have tested it on Arc 1.37.0 (48361) and Chrome 123.0.6312.105 (Official Build) (arm64):
> 
> ![image](https://private-user-images.githubusercontent.com/1407009/320165229-bf11852e-093e-4f6b-884b-bff8cfb3b194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTQ3NTYsIm5iZiI6MTcxMjQ5NDQ1NiwicGF0aCI6Ii8xNDA3MDA5LzMyMDE2NTIyOS1iZjExODUyZS0wOTNlLTRmNmItODg0Yi1iZmY4Y2ZiM2IxOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMTI1NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRiNjQxMDVlZTg4NzA0YTY4YTU3OTcxODlkODU4MzBiZjNkZGZlYzdhYzhjMGU4MGU3ZjM3OGM2MGI3YTdhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PT06Kf7BSvxDlYFKotUJHoat32L5ieN1mEDSx6GTuOw)

**Comment by iMuFeng** [comment]
> I had double check this issue. Yes, as your screenshot demonstrating the image was uploaded successfully. 
> 
> 
> 
> But the issue is that we can't download it by clicking the attachment icon on the submissions page, which is showing all data as a table for the form admin.
> 
> 
> 
> 
> 
> > The images will only start uploading after the form is submitted. I have tested it on Arc 1.37.0 (48361) and Chrome 123.0.6312.105 (Official Build) (arm64):
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/1407009/320165229-bf11852e-093e-4f6b-884b-bff8cfb3b194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTQ3NTYsIm5iZiI6MTcxMjQ5NDQ1NiwicGF0aCI6Ii8xNDA3MDA5LzMyMDE2NTIyOS1iZjExODUyZS0wOTNlLTRmNmItODg0Yi1iZmY4Y2ZiM2IxOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMTI1NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRiNjQxMDVlZTg4NzA0YTY4YTU3OTcxODlkODU4MzBiZjNkZGZlYzdhYzhjMGU4MGU3ZjM3OGM2MGI3YTdhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PT06Kf7BSvxDlYFKotUJHoat32L5ieN1mEDSx6GTuOw)
> 
> 
> 
> 

We have confirmed that the attachment download is a bug and it will be fixed in the next version.

**Comment by iMuFeng** [comment]
v0.0.6 is released.
