### ISSUE TITLE
Submissions not properly displayed after schema change

### ISSUE THREAD

**Issue by 0kenx** [heyform/heyform#29]
If you change the schema after a form is published, new submissions are not properly displayed.

**To Reproduce**
1. Publish a form and make a submission, you'll see 1 entry.
2. Change the schema by deleting a field and adding one.
3. Make another submission. You'll see "2 submissions" in summary, but only 1 submission in details. CSV export shows both submissions correctly.

**HeyForm (please complete the following information):**
- Install: self hosted
- Version: 0.0.5

**Comment by iMuFeng** [comment]
Can you upload a sample CSV file here and type of the question.

**Comment by 0kenx** [comment]
I think it's an easy bug to replicate. Let me know if you need more info.
