### ISSUE TITLE
Trojan Alert on Downloaded Zip

### ISSUE THREAD

**Issue by sudeephazra** [heyform/heyform#46]
**To Reproduce**
1. Download the repository as zip

**Expected behavior**
Not a trojan alert 

**Screenshots**
![image](https://github.com/heyform/heyform/assets/642449/864c22ab-81cc-41c9-b980-e5b6f40b888d)

**HeyForm (please complete the following information):**
- Install: [self hosted]
- Version: [commit sha if self hosted]

**Desktop (please complete the following information):**
- OS: Windows
- Browser: All
- Version: 11

**Comment by iMuFeng** [comment]
I believe this is a false positive from Microsoft Security, and I have already submitted an appeal to them.

**Comment by sudeephazra** [comment]
Thanks for the prompt response @iMuFeng
