### ISSUE TITLE
Use S3 to store static files

### ISSUE THREAD

**Issue by iMuFeng** [heyform/heyform#64]
### Discussed in https://github.com/orgs/heyform/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **fkammer** April 18, 2024</sup>
Uploaded files are currently stored locally in `/app/static/upload` and lost when the container is destroyed.

Using a persistent volume works but you're then unable to run multiple heyform instances in parallel for load balancing. Most Kubernetes providers do not support Volumes with `ReadWriteMany` capabilities.

In my opinion the best alternative would be a generic S3 connection.</div>

**Comment by admirsaheta** [comment]
A better alternative to this might be **Supabase Storage**
