### ISSUE TITLE
Integrated Developer Documentation Hosting

### ISSUE THREAD

**Issue by iMuFeng** [heyform/heyform#65]
### Discussed in https://github.com/orgs/heyform/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **builtcuriously** April 21, 2024</sup>
The ability to host and manage the developer documentation directly within the HeyForm repository would allow self-hosters and contributors to create, update, and access documentation alongside the codebase. 

## Benefits
- locally accessibility 
- versioned to last sync to origin 
- community contributions 

## Implementation Suggestion
A separate directory within the monorepo such as `/packages/docs`. The existing docs are in Notion markdown and thus formatted appropriately.

Thank you for considering this suggestion ☺️</div>

**Comment by dearroy** [comment]
This is completed. Please refer to the [reply](https://github.com/orgs/heyform/discussions/62#discussioncomment-10074369) in the original discussion.
