### ISSUE TITLE
Custom Domains going wrong

### ISSUE THREAD

**Issue by Zakichanu** [heyform/heyform#68]
So, I subscribed to the premium plan. I have a domain for all the services I deploy for my company. 

Naturally, I put a subdomain for all my forms. I followed the documentation of the heyform, which was to put a CNAME on my DNS config etc etc. 

It work perfectly well, since today, when I click on the link of one of my forms, I got this SSL error : `ERR_SSL_PROTOCOL_ERROR`

**To Reproduce**
1. Go to `https://forms.rmacharge.fr/f/ay2MSIXf`
2. See error

**Expected behavior**
Should see my form

**Screenshots**
![image](https://github.com/heyform/heyform/assets/49374657/9480e12e-e538-42c8-9d11-71c6477b8a2e)

**HeyForm (please complete the following information):**
- Install: heyform.net
- Version: heyform.net

**Desktop (please complete the following information):**
- OS: MacOS / also tried on IOS 
- Browser: Chrome / Safari
- Version: latest

**Mobile (please complete the following information):**
- Device: iPhone 13
- OS: Safari

**Comment by Zakichanu** [comment]
I resolved it by changing the subdomain, but can you look into it

**Comment by iMuFeng** [comment]
We apologize for the inconvenience. After clicking 'Save' on the dashboard, our server was unable to submit forms.rmacharge.fr to our domain server, despite the successful notification on the dashboard. We will fix this issue promptly.

**Comment by Zakichanu** [comment]
Thanks to you! I update the subdomain to form.rmacharge.fr (without the S), for your information
