### ISSUE TITLE
Files served from CDN for local development setup (and probably when self-hosting)

### ISSUE THREAD

**Issue by raphj** [heyform/heyform#84]
**To Reproduce**
1. [Setup HeyForm for local development](https://docs.heyform.net/local-development)
2. Load HeyForm in the browser
3. Notice requests to cdn.cloudflare.com

**Expected behavior**

No external requests should be done.
HeyForm should be fully working in a train without an internet connection, for development.
Self hosted should be fully self hosted, or the CDN use should be advertised and optional.

- Install: self hosted
- Version: c06ce1e39a5cd5f942eefb633ad81ebaf5566a6c (Release v0.0.10, Sun May 5 12:17:04 2024 +0800)

- OS: openSUSE Tumbleweed (GNU/Linux)
- Browser: Firefox
- Version 125.0.3

Note: I noticed this because I was on a bad 3G connection and HeyForm was unexpectedly (local install) slow to load.

**Comment by iMuFeng** [comment]
The flag icon currently uses [CDN ](https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/4.1.5/css/flag-icons.min.css), we will replace it with an npm package in the next version.
