### ISSUE TITLE
Wrong sequence of steps when one step is optional

### ISSUE THREAD

**Issue by anarion80** [heyform/heyform#91]
When a form contains an optional step in the middle of the flow, and it is filled, then it is not possible to submit the form as it goes back to that optional step.

When the optional step is left empty, then the form is correctly submitted.

Example form: https://heyform.net/f/8H01jfZw

**To Reproduce**
1. Create a form that has a few steps, one of which is optional (not required)
2. Fill the form, including the optional step.
3. Go to the end of the form and submit it.

**Expected behavior**
The form is submitted and proceeds to the Thank You step.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**HeyForm (please complete the following information):**
- Install: both heyform.net and self-hosted
- Version: a9f764e6a475ff9075e1297737c1850715112c22

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Edge
- Version: 124.0.2478.97

**Comment by iMuFeng** [comment]
Can't reproduce it. The red boxes in the image indicate two optional questions.

![image](https://github.com/heyform/heyform/assets/1407009/1d959a88-c719-4105-8868-693035ad762e)

**Comment by anarion80** [comment]
Ah, ok, so the problem is different. Indeed, when you enter all the 5 address fields then it works. But since the whole address step is not mandatory, user can only enter Address for example, without City, Country, etc. - there is no checking each individual field. The user can progress to the next step. But then at the end, the user is brought back to the Address step and the system expects all those fields to be filled out, without any indication to the user. It just keeps getting back to the step, there is no warning or error, there are only errors in the console:

![image](https://github.com/heyform/heyform/assets/2185791/ffbe6fe0-cab4-4fdf-8ce3-533244c0f1b8)

This I think is still wrong. If the whole step is not mandatory, then the system should not force all fields to be filled out OR there should be an indication back to the user about this at least.
