### ISSUE TITLE
Issues when adding default US phone number

### ISSUE THREAD

**Issue by anarion80** [heyform/heyform#92]
When a form contains a Phone step, it is by default set to US phone number:
![image](https://github.com/heyform/heyform/assets/2185791/ae784698-8d33-415a-8a34-f4b958c9f82e)

when you just type the numbers, you can't submit it:
![image](https://github.com/heyform/heyform/assets/2185791/8a996629-c5c3-4664-9dc6-79a53c339323)

You have to type the parenthesis as well, which is kind of annoying and superfluous

Example form: https://heyform.net/f/8H01jfZw

**To Reproduce**
1. Create a form that has a few steps, one of which is optional (not required)
2. Fill the form, including the optional step.
3. Go to the end of the form and submit it.

**Expected behavior**
The form is submitted and proceeds to the Thank You step.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**HeyForm (please complete the following information):**
- Install: both heyform.net and self-hosted
- Version: a9f764e6a475ff9075e1297737c1850715112c22

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Edge
- Version: 124.0.2478.97

**Comment by iMuFeng** [comment]
You can test the validity of a phone number here: https://catamphetamine.github.io/libphonenumber-js/?parseCountry=US&parseValue=1112223333&asYouTypeCountry=US&findNumbersCountry=US&findNumbersText=For%20more%20details%20call%20%2B7%20(800)%20555-35-35%20internationally%20or%20reach%20the%20local%20US%20branch%20at%20(213)%20373-4253%20ext.%201234%20for%20paid%20customer%20support.

**Comment by anarion80** [comment]
Right. You just really need to enter the number like in the placeholder, with parenthesis. This is really annoying, but I guess this is a feature of the underlying library not Heyform.
