### ISSUE TITLE
Custom link doesn't work

### ISSUE THREAD

**Issue by Zakichanu** [heyform/heyform#99]
**To Reproduce**
1. Go [here](https://form.rmacharge.fr/f/9u9Rh31P)
2. Wait for the timeout
3. See error

**Expected behavior**
I think there is down on your server side, I thinks is a part of your database that isn't responding

**Screenshots**
![image](https://github.com/heyform/heyform/assets/49374657/e5a4ca7e-3f76-49d5-ac73-4a1b9ec3448b)
<br />
![IMG_1619154CAB77-1](https://github.com/heyform/heyform/assets/49374657/e8bdc2ea-c750-43b7-bb33-9b0e4cccdd0b)

**HeyForm (please complete the following information):**
- Install: heyform.net
- Version: Latest

**Comment by iMuFeng** [comment]
Our domain server is currently undergoing maintenance and will be back online soon.

**Comment by Zakichanu** [comment]
Thanks for your response

**Comment by iMuFeng** [comment]
The server is back online now.
